INSERT INTO account
(username,
 password,
 is_sell,
 is_admin,
 fullname,
 phone,
 email,
 city,
 district,
 ward)
VALUES ('admin',
        '123456',
        1,
        1,
        'Administrator',
        '0900000001',
        'admin@shop.com',
        'Ho Chi Minh',
        'District 1',
        'Ben Nghe'),

       ('seller01',
        '123456',
        1,
        0,
        'Nguyen Van A',
        '0900000002',
        'seller01@shop.com',
        'Ho Chi Minh',
        'District 3',
        'Ward 5'),

       ('customer01',
        '123456',
        0,
        0,
        'Tran Thi B',
        '0900000003',
        'customer01@gmail.com',
        'Ha Noi',
        'Cau Giay',
        'Dich Vong');